---
- id: buf-lint
  name: 'buf lint'
  entry: 'run-buf-lint.sh'
  language: 'script'
  files: '\.proto$'
  pass_filenames: true
  description: 'Runs `buf lint`'
- id: buf-breaking
  name: 'buf breaking'
  entry: 'run-buf-breaking.sh'
  language: 'script'
  files: '\.proto$'
  pass_filenames: true
  description: 'Runs `buf breaking`'
